=== hamsterxc/raytracing/src/main/resources/scene/scene.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://lonebytesoft.com"
           targetNamespace="http://lonebytesoft.com"
           elementFormDefault="qualified">

    <!-- Scene -->

    <xs:element type="sceneType" name="scene"/>

    <xs:complexType name="sceneType">
        <xs:all>
            <xs:element type="colorType" name="colorDefault"/>
            <xs:element type="coordinatesType" name="eye"/>
            <xs:element type="screenType" name="screen"/>
            <xs:element type="multipleShapesType" name="shapes" minOccurs="0"/>
            <xs:element type="sceneLightsType" name="lights" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="screenType">
        <xs:all>
            <xs:element type="singleShapeType" name="shape"/>
            <xs:element type="coordinatesType" name="from"/>
            <xs:element type="coordinatesType" name="to"/>
            <xs:element type="coordinatesType" name="resolution"/>
            <xs:element type="screenPixelColoringType" name="pixelColoring"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="screenPixelColoringType">
        <xs:choice>
            <xs:element type="screenPixelColoringSimpleType" name="simple"/>
            <xs:element type="screenPixelColoringSupersamplingType" name="supersampling"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="screenPixelColoringSimpleType"/>

    <xs:complexType name="screenPixelColoringSupersamplingType">
        <xs:all>
            <xs:element type="xs:integer" name="multiplier"/>
            <xs:element type="colorType" name="colorDefault"/>
        </xs:all>
    </xs:complexType>

    <!-- Shapes -->

    <xs:complexType name="singleShapeType">
        <xs:choice>
            <xs:element type="orthotopeType" name="orthotope"/>
            <xs:element type="ballType" name="ball"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="multipleShapesType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="orthotopeType" name="orthotope"/>
            <xs:element type="ballType" name="ball"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="orthotopeType">
        <xs:all>
            <xs:element type="coordinatesType" name="base"/>
            <xs:element type="vectorsType" name="vectors"/>
            <xs:element type="xs:boolean" name="infinite"/>
            <xs:element type="shapeLayersType" name="layers" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ballType">
        <xs:all>
            <xs:element type="coordinatesType" name="center"/>
            <xs:element type="xs:decimal" name="radius"/>
            <xs:element type="shapeLayersType" name="layers" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <!-- Shape layers -->

    <xs:complexType name="shapeLayersType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="shapeLayerReflectingType" name="reflecting"/>
            <xs:element type="shapeLayerRefractingType" name="refracting"/>
            <xs:element type="shapeLayerSolidColoredType" name="solidcolored"/>
            <xs:element type="shapeLayerTexturedType" name="textured"/>
            <xs:element type="shapeLayerTransparentType" name="transparent"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="baseShapeLayerType">
        <xs:attribute type="xs:decimal" name="weight" use="required"/>
    </xs:complexType>

    <xs:complexType name="shapeLayerReflectingType">
        <xs:complexContent>
            <xs:extension base="baseShapeLayerType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="shapeLayerRefractingType">
        <xs:complexContent>
            <xs:extension base="baseShapeLayerType">
                <xs:all>
                    <xs:element type="xs:decimal" name="coeff"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="shapeLayerSolidColoredType">
        <xs:complexContent>
            <xs:extension base="baseShapeLayerType">
                <xs:all>
                    <xs:element type="colorType" name="color"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="shapeLayerTexturedType">
        <xs:complexContent>
            <xs:extension base="baseShapeLayerType">
                <xs:all>
                    <xs:element type="shapeLayerTexturedTextureType" name="texture"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="shapeLayerTexturedTextureType">
        <xs:choice>
            <xs:element type="shapeLayerTexturedTextureCheckersType" name="checkers"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="shapeLayerTexturedTextureCheckersType">
        <xs:all>
            <xs:element type="shapeLayerTexturedTextureCheckersMultipliersType" name="multipliers"/>
            <xs:element type="shapeLayerTexturedTextureCheckersColorsType" name="colors"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="shapeLayerTexturedTextureCheckersMultipliersType">
        <xs:sequence>
            <xs:element type="xs:decimal" name="multiplier" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="shapeLayerTexturedTextureCheckersColorsType">
        <xs:sequence>
            <xs:element type="colorType" name="color" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="shapeLayerTransparentType">
        <xs:complexContent>
            <xs:extension base="baseShapeLayerType"/>
        </xs:complexContent>
    </xs:complexType>

    <!-- Lights -->

    <xs:complexType name="sceneLightsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="sceneLightAmbientType" name="ambient"/>
            <xs:element type="sceneLightConeType" name="cone"/>
            <xs:element type="sceneLightPointType" name="point"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="sceneLightAmbientType">
        <xs:all>
            <xs:element type="xs:decimal" name="brightness"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="sceneLightConeType">
        <xs:all>
            <xs:element type="coordinatesType" name="source"/>
            <xs:element type="vectorType" name="direction"/>
            <xs:element type="xs:decimal" name="angle"/>
            <xs:element type="xs:decimal" name="brightness"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="sceneLightPointType">
        <xs:all>
            <xs:element type="coordinatesType" name="source"/>
            <xs:element type="xs:decimal" name="brightness"/>
        </xs:all>
    </xs:complexType>

    <!-- Common -->

    <xs:complexType name="coordinatesType">
        <xs:attribute type="xs:string" name="coordinates" use="required"/>
    </xs:complexType>

    <xs:complexType name="vectorType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="vectorRotateType" name="rotate"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="coordinates" use="required"/>
    </xs:complexType>

    <xs:complexType name="vectorRotateType">
        <xs:all>
            <xs:element type="xs:integer" name="axisFirst"/>
            <xs:element type="xs:integer" name="axisSecond"/>
            <xs:element type="xs:decimal" name="angle"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="vectorsType">
        <xs:sequence>
            <xs:element type="vectorType" name="vector" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

</xs:schema>

=== hamsterxc/raytracing/src/main/resources/scene/cone_light.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns="http://lonebytesoft.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://lonebytesoft.com scene.xsd">

    <colorDefault>0 0 0</colorDefault>

    <eye coordinates="0 0 0"/>

    <screen>
        <shape>
            <orthotope>
                <base coordinates="100 -100 -100"/>
                <vectors>
                    <vector coordinates="0 200 0"/>
                    <vector coordinates="0 0 200"/>
                </vectors>
                <infinite>false</infinite>
            </orthotope>
        </shape>
        <from coordinates="1 1"/>
        <to coordinates="0 0"/>
        <resolution coordinates="1024 1024"/>
        <pixelColoring>
            <supersampling>
                <multiplier>2</multiplier>
                <colorDefault>0 0 0</colorDefault>
            </supersampling>
        </pixelColoring>
    </screen>

    <shapes>
        <orthotope>
            <base coordinates="0 0 -300"/>
            <vectors>
                <vector coordinates="100 0 0"/>
                <vector coordinates="0 100 0"/>
            </vectors>
            <infinite>true</infinite>
            <layers>
                <textured weight="1">
                    <texture>
                        <checkers>
                            <multipliers>
                                <multiplier>2</multiplier>
                                <multiplier>2</multiplier>
                            </multipliers>
                            <colors>
                                <color>0 0 0</color>
                                <color>1 1 1</color>
                            </colors>
                        </checkers>
                    </texture>
                </textured>
            </layers>
        </orthotope>

        <ball>
            <center coordinates="700 0 -100"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>1 0 0</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </ball>

        <ball>
            <center coordinates="500 500 -100"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>0 1 0</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </ball>

        <ball>
            <center coordinates="500 -500 -100"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>0 0 1</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </ball>
    </shapes>
    
    <lights>
        <ambient>
            <brightness>-9</brightness>
        </ambient>

        <cone>
            <source coordinates="600 100 500"/>
            <direction coordinates="0 0 -1"/>
            <angle>0.7854</angle>
            <brightness>5000000</brightness>
        </cone>
    </lights>
</scene>

=== hamsterxc/raytracing/src/main/resources/scene/balls_cube.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns="http://lonebytesoft.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://lonebytesoft.com scene.xsd">

    <colorDefault>0 0 0</colorDefault>

    <eye coordinates="0 0 0"/>

    <screen>
        <shape>
            <orthotope>
                <base coordinates="100 -100 -100"/>
                <vectors>
                    <vector coordinates="0 200 0"/>
                    <vector coordinates="0 0 200"/>
                </vectors>
                <infinite>false</infinite>
            </orthotope>
        </shape>
        <from coordinates="1 1"/>
        <to coordinates="0 0"/>
        <resolution coordinates="1024 1024"/>
        <pixelColoring>
            <supersampling>
                <multiplier>3</multiplier>
                <colorDefault>0 0 0</colorDefault>
            </supersampling>
        </pixelColoring>
    </screen>

    <shapes>
        <orthotope>
            <base coordinates="0 0 -300"/>
            <vectors>
                <vector coordinates="100 0 0"/>
                <vector coordinates="0 100 0"/>
            </vectors>
            <infinite>true</infinite>
            <layers>
                <textured weight="1">
                    <texture>
                        <checkers>
                            <multipliers>
                                <multiplier>2</multiplier>
                                <multiplier>2</multiplier>
                            </multipliers>
                            <colors>
                                <color>0 0 0</color>
                                <color>1 1 1</color>
                            </colors>
                        </checkers>
                    </texture>
                </textured>
                <reflecting weight="1"/>
            </layers>
        </orthotope>

        <ball>
            <center coordinates="500 500 -100"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>0 1 0</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </ball>

        <ball>
            <center coordinates="500 -500 -100"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>0 0 1</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </ball>
        
        <orthotope>
            <base coordinates="600 -200 200"/>
            <vectors>
                <vector coordinates="400 0 0">
                    <rotate>
                        <axisFirst>1</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>1</axisSecond>
                        <angle>0.7854</angle>
                    </rotate>
                </vector>
                <vector coordinates="0 400 0">
                    <rotate>
                        <axisFirst>1</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>1</axisSecond>
                        <angle>0.7854</angle>
                    </rotate>
                </vector>
                <vector coordinates="0 0 400">
                    <rotate>
                        <axisFirst>1</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>2</axisSecond>
                        <angle>0.5236</angle>
                    </rotate>
                    <rotate>
                        <axisFirst>0</axisFirst>
                        <axisSecond>1</axisSecond>
                        <angle>0.7854</angle>
                    </rotate>
                </vector>
            </vectors>
            <infinite>false</infinite>
            <layers>
                <textured weight="1">
                    <texture>
                        <checkers>
                            <multipliers>
                                <multiplier>1</multiplier>
                                <multiplier>0</multiplier>
                            </multipliers>
                            <colors>
                                <color>0 1 1</color>
                                <color>1 0 0</color>
                                <color>0 1 0</color>
                                <color>0 0 1</color>
                                <color>1 1 0</color>
                                <color>1 0 1</color>
                            </colors>
                        </checkers>
                    </texture>
                </textured>
                <reflecting weight="1"/>
            </layers>
        </orthotope>
    </shapes>

    <lights>
        <point>
            <source coordinates="600 0 400"/>
            <brightness>500000</brightness>
        </point>
    </lights>

</scene>

=== hamsterxc/raytracing/src/main/resources/scene/ball_refracting.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns="http://lonebytesoft.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://lonebytesoft.com scene.xsd">

    <colorDefault>0 0 0</colorDefault>
    
    <eye coordinates="0 0 0"/>

    <screen>
        <shape>
            <orthotope>
                <base coordinates="100 -100 -100"/>
                <vectors>
                    <vector coordinates="0 200 0"/>
                    <vector coordinates="0 0 200"/>
                </vectors>
                <infinite>false</infinite>
            </orthotope>
        </shape>
        <from coordinates="1 1"/>
        <to coordinates="0 0"/>
        <resolution coordinates="1024 1024"/>
        <pixelColoring>
            <supersampling>
                <multiplier>3</multiplier>
                <colorDefault>0 0 0</colorDefault>
            </supersampling>
        </pixelColoring>
    </screen>
    
    <shapes>
        <orthotope>
            <base coordinates="0 0 -300"/>
            <vectors>
                <vector coordinates="100 0 0"/>
                <vector coordinates="0 100 0"/>
            </vectors>
            <infinite>true</infinite>
            <layers>
                <textured weight="1">
                    <texture>
                        <checkers>
                            <multipliers>
                                <multiplier>2</multiplier>
                                <multiplier>2</multiplier>
                            </multipliers>
                            <colors>
                                <color>0 0 0</color>
                                <color>1 1 1</color>
                            </colors>
                        </checkers>
                    </texture>
                </textured>
            </layers>
        </orthotope>

        <ball>
            <center coordinates="700 -200 0"/>
            <radius>200</radius>
            <layers>
                <refracting weight="1">
                    <coeff>1.5</coeff>
                </refracting>
            </layers>
        </ball>

        <ball>
            <center coordinates="1400 100 100"/>
            <radius>300</radius>
            <layers>
                <textured weight="1">
                    <texture>
                        <checkers>
                            <multipliers>
                                <multiplier>20</multiplier>
                                <multiplier>20</multiplier>
                            </multipliers>
                            <colors>
                                <color>1 1 1</color>
                                <color>1 0 0</color>
                                <color>0 1 0</color>
                                <color>0 0 1</color>
                                <color>1 1 0</color>
                            </colors>
                        </checkers>
                    </texture>
                </textured>
            </layers>
        </ball>
    </shapes>
    
</scene>

=== hamsterxc/raytracing/src/main/resources/scene/basic.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns="http://lonebytesoft.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://lonebytesoft.com scene.xsd">

    <colorDefault>0 0 0</colorDefault>

    <eye coordinates="0 0 0"/>

    <screen>
        <shape>
            <orthotope>
                <base coordinates="100 100 100"/>
                <vectors>
                    <vector coordinates="0 -200 0"/>
                    <vector coordinates="0 0 -200"/>
                </vectors>
                <infinite>false</infinite>
            </orthotope>
        </shape>
        <from coordinates="0 0"/>
        <to coordinates="1 1"/>
        <resolution coordinates="256 256"/>
        <pixelColoring>
            <simple/>
        </pixelColoring>
    </screen>

    <shapes>
        <orthotope>
            <base coordinates="0 0 -300"/>
            <vectors>
                <vector coordinates="100 0 0"/>
                <vector coordinates="0 100 0"/>
            </vectors>
            <infinite>true</infinite>
            <layers>
                <solidcolored weight="1">
                    <color>1 1 1</color>
                </solidcolored>
                <reflecting weight="1"/>
            </layers>
        </orthotope>

        <ball>
            <center coordinates="700 0 0"/>
            <radius>200</radius>
            <layers>
                <solidcolored weight="1">
                    <color>1 0 0</color>
                </solidcolored>
                <transparent weight="1"/>
            </layers>
        </ball>
    </shapes>

    <lights>
        <ambient>
            <brightness>-5</brightness>
        </ambient>
        <point>
            <source coordinates="600 -100 500"/>
            <brightness>1000000</brightness>
        </point>
    </lights>

</scene>
